#server:
#  port: 8080

##  注释
# 自定义属性

itmayiedu:
  httpurl: http://localhost.com
  name: 课堂
  students:
    money: 18000

#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp

#通过下面的配置启用所有的监控端点，默认情况下，这些端点是禁用的
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

info:
  itmayiedu: yushengjun
  addres: www.itmayiedu.com




